default_platform(:android)

platform :android do
  desc "Send result to slack"
  lane :send_result do
    version = sh("yarn get-version-number-android").split("\n")[2]
    build = sh("yarn get-build-number-android").split("\n")[2]
    js_version = sh("yarn get-version-number-js").split("\n")[2]
    slack(
      message: "앱이 배포되었습니다🚀",
      slack_url: "https://hooks.slack.com/services/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",
      payload: {
        "Android version" => version + " " + "(" + build + ")",
        "JS version" => js_version
      }
    )
  end

  desc "Submit a new version to the internal testing track"
  lane :beta do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft'
    )
    send_result
  end

  desc "Submit a new version to the production"
  lane :release do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'release'
    )
    upload_to_play_store(
      track: 'production'
    )
    send_result
  end
end
